### ISSUE TITLE
Puddles should not be directly breakable

### ISSUE THREAD

**Issue by bravely-beep** [TeamMidnightDust/Puddles#10]
Currently (on 1.18.1), puddles can be broken instantly by left clicking them. They play the stone breaking sound and drop blue particles that have collision. It would make much more sense if they were intangible (i.e. trying to break them should break the block behind them instead), and if the block beneath them is broken, they should just disappear with no sound or particles.

**Comment by BravelyPeculiar** [comment]
I don't see why changing the behaviour would be a problem? You could remove annoying puddles with a bucket, or by placing a block inside the block the puddle currently occupies, replacing it (just like vanilla water blocks).

Even if the behaviour is kept as-is, though, the breaking sound effect and particle behaviour should be changed to behave more like a liquid.

**Comment by Motschen** [comment]
Fixed in 2.0.0 :D
