### ISSUE TITLE
1.20.1 Crash on load

### ISSUE THREAD

**Issue by Gamerbolts** [TeamMidnightDust/Puddles#16]
Hello, I added your mod to my pack and got a crash. The log is here 
[latest.log](https://github.com/user-attachments/files/17063988/latest.log)
It's not coming up as a crash log just a regular log. It states Error creating Mixin config puddles.mixins.json for mod puddles

Using 
Fabric 0.16.5
Fabric API  0.92.2+1.20.1
Puddles 2.0.0+1.20.1
MidnightLib 1.4.1

Any help is appreciated. Thank you!

**Comment by Motschen** [comment]
Fixed, was as simple as changing two characters :)
