### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by RDKRACZ** [TeamMidnightDust/Puddles#3]
After the separation from Visual Overhaul, there is no config file. Please add an option to disable filling water bottles, some mods add other bottles or flasks and they can't be filled. Not sure if a puddle is enough to fill a bottle too.

**Comment by Motschen** [comment]
There never was a config file for the puddles part, everything can be configured via gamerules.
I think a puddle filling a bottle is totally balanced, you could also do it with a real life puddle, also, you literally have unlimited water in the game, so it's definitely not overpowered.
